/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_KBD_STATUS_PB_H_INCLUDED
#define PB_KBD_STATUS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _KBD_Test {
    pb_callback_t data;
} KBD_Test;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define KBD_Test_init_default                    {{{NULL}, NULL}}
#define KBD_Test_init_zero                       {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define KBD_Test_data_tag                        1

/* Struct field encoding specification for nanopb */
#define KBD_Test_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   data,              1)
#define KBD_Test_CALLBACK pb_default_field_callback
#define KBD_Test_DEFAULT NULL

extern const pb_msgdesc_t KBD_Test_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define KBD_Test_fields &KBD_Test_msg

/* Maximum encoded size of messages (where known) */
/* KBD_Test_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
